version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  assignees:
  - cobexer
  ignore:
  - dependency-name: org.samba.jcifs:jcifs
    versions:
    - ">= 1.3.18-kohsuke-1.a"
    - "< 1.3.19"
